In [1]:
import numpy as np

In [3]:
marks = np.random.randint(40, 100, 11)
print(marks)
print(marks.mean())
print(np.mean(marks))

[95 77 42 91 41 78 49 46 67 50 85]
65.54545454545455
65.54545454545455


### Task 1
At the every year tell me balance for 10 years
Clue: General formula
1102.5 -> 1000 +
[1050, 1102.5 ...., ]
 

In [33]:
initial_investment = 1_000
int_rate = 0.05

years_array = np.arange(1,11)

balances = initial_investment*(1+int_rate) ** years_array

balances

array([1050.        , 1102.5       , 1157.625     , 1215.50625   ,
       1276.2815625 , 1340.09564063, 1407.10042266, 1477.45544379,
       1551.32821598, 1628.89462678])

### Task 2
At the year of ten years what will be the balance

In [ ]:
initial_investment = 1_000
int_rate = 0.05
years_array = np.arange(1,11)

balances = initial_investment * (1 + int_rate) ** years_array

balances[-1]


np.float64(1628.894626777442)

In [21]:
initial_investment = 1_000
int_rate = 0.05
years = 10

# years_array = np.arange(years + 1)

balances = initial_investment * (1 + int_rate) ** years

balances


1628.894626777442

### Task 3
How is much % its increase as compared to first year

In [ ]:
initial_investment = 1_000
int_rate = 0.05
years = 10

# years_array = np.arange(years + 1)
balances_one = initial_investment * (1 + int_rate) ** 1
balances_ten = initial_investment * (1 + int_rate) ** years

bal_diff = (balances_ten - balances_one)/balances_one

bal_diff_percentage = bal_diff * 100

bal_diff_percentage


55.132821597851624

In [29]:
initial_investment = 1_000
int_rate = 0.05
years_array = np.arange(1, 11)

balances = initial_investment * (1 + int_rate) ** years_array

balances_one = balances[0]
balances_ten = balances[-1]

bal_diff = (balances_ten - balances_one) / balances_one
bal_diff_percentage = bal_diff * 100

bal_diff_percentage


np.float64(55.132821597851624)

In [ ]:
initial_investment = 1_000
int_rate = 0.05
years_array = np.arange(1, 11)

balances = initial_investment * (1 + int_rate) ** years_array

bal_diff_percentage = ((balances[-1] - initial_investment) / initial_investment) * 100

bal_diff_percentage

np.float64(62.8894626777442)

## Useful methods
- max, min - argmax, argmin

In [37]:
salaries = np.random.randint(1000, 10000,10)
print (salaries)

[1280 8177 7831 9754 1049 9875 6425 9349 7853 8039]


In [38]:
np.min(salaries)

np.int32(1049)

In [39]:
np.argmin(salaries)

np.int64(4)

In [40]:
nums = np.random.randint(1, 4, 10)

nums


array([2, 3, 2, 1, 3, 3, 1, 3, 2, 2], dtype=int32)

In [46]:
nums = np.random.randint(1, 4, 10)

np.unique_values(nums)


array([1, 2, 3], dtype=int32)