In [1]:
import numpy as np


In [2]:
marks1 = [90,80,20,40]

print(marks1*2)

[90, 80, 20, 40, 90, 80, 20, 40]


In [10]:
marks1 = [90, 80, 20, 40]

print([mark * 2 for mark in marks1])

[180, 160, 40, 80]


In [13]:
marks2 = np.array([90, 80, 20, 40])

print(marks2 * 2)

[180 160  40  80]


In [18]:
5*np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [20]:
np.zeros(20) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [25]:
np.arange(10) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
odd = np.arange(1,10,2)

odd


array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10) - 1

In [ ]:
np.arange(10) + np.arange(10)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.array([9,2,3]) + np.array([1,2,5])

array([10,  4,  8])

In [33]:
[9,2,3] + [1,2,5]

[9, 2, 3, 1, 2, 5]

In [34]:
np.arange(1,11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
first_ten = np.arange(1,11)
five_bm = first_ten > 5
first_ten[five_bm]

array([ 6,  7,  8,  9, 10])

In [36]:
first_ten = np.arange(1,11)
first_ten[first_ten> 5]

array([ 6,  7,  8,  9, 10])