In [1]:
import numpy as np


In [2]:
marks1 = [90,80,20,40]

print(marks1*2)

[90, 80, 20, 40, 90, 80, 20, 40]


In [10]:
marks1 = [90, 80, 20, 40]

print([mark * 2 for mark in marks1])

[180, 160, 40, 80]


In [13]:
marks2 = np.array([90, 80, 20, 40])

print(marks2 * 2)

[180 160  40  80]


In [18]:
5*np.ones(20)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [20]:
np.zeros(20) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [25]:
np.arange(10) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
odd = np.arange(1,10,2)

odd


array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10) - 1

In [ ]:
np.arange(10) + np.arange(10)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.array([9,2,3]) + np.array([1,2,5])

array([  9,   4, 243])

In [ ]:
np.array([9,2,3]) ** np.array([1,2,5])

In [33]:
[9,2,3] + [1,2,5]

[9, 2, 3, 1, 2, 5]

In [34]:
np.arange(1,11) > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
first_ten = np.arange(1,11)
five_bm = first_ten > 5
first_ten[five_bm]

array([ 6,  7,  8,  9, 10])

In [36]:
first_ten = np.arange(1,11)
first_ten[first_ten> 5]

array([ 6,  7,  8,  9, 10])

In [40]:
np.arange(0,201,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [55]:
numbers = np.arange(1,201)
even_numbers = numbers % 2 == 0
print(numbers[even_numbers])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [51]:
numbers = np.arange(1,201)
even_numbers = np.arange(1,201) % 2 == 0
print(numbers[even_numbers])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [60]:
numbers = np.arange(1,201)

numbers[np.arange(1,201) % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [62]:
ages = np.random.randint(18,60,50)
ages_list = ages.tolist()

ages_list

[54,
 46,
 46,
 26,
 18,
 26,
 51,
 32,
 42,
 28,
 38,
 56,
 30,
 29,
 34,
 47,
 58,
 56,
 24,
 30,
 54,
 51,
 18,
 56,
 52,
 48,
 39,
 45,
 48,
 46,
 53,
 34,
 44,
 18,
 19,
 44,
 51,
 24,
 29,
 29,
 43,
 29,
 36,
 46,
 20,
 48,
 58,
 58,
 37,
 30]

In [63]:
ages = np.random.randint(18,60,50)
# ages_list = ages.tolist()

ages[ages> 25]

array([52, 31, 36, 29, 56, 39, 51, 44, 55, 53, 33, 40, 38, 27, 44, 52, 43,
       30, 38, 59, 28, 40, 45, 26, 58, 49, 54, 28, 35, 51, 31, 59, 56, 59,
       31, 36, 56, 56, 29, 54], dtype=int32)